name: Update Ticker (täglich)

on:
  schedule:
    - cron: "0 4 * * *"   # ca. 06:00 Europe/Berlin
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run update script (no npm)
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          node -v
          test -f scripts/update_ticker.mjs || (echo "scripts/update_ticker.mjs fehlt" && exit 1)
          node scripts/update_ticker.mjs
          echo "----- ticker.json (preview) -----"
          cat ticker.json || true
          echo "---------------------------------"

      - name: Commit & push if changed
        uses: EndBug/add-and-commit@v9
        with:
          add: "ticker.json"
          message: "chore: daily ticker update"
          default_author: github_actions

