name: Update Ticker (täglich)

on:
  schedule:
    - cron: "0 4 * * *"   # ca. 06:00 Europe/Berlin
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: ticker-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0       # wichtig für rebase/merge

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run update script (no npm)
        env:
          FRED_API_KEY: ${{ secrets.FRED_API_KEY }}
        run: |
          node -v
          test -f scripts/update_ticker.mjs || (echo "FEHLT: scripts/update_ticker.mjs" && exit 1)
          node scripts/update_ticker.mjs
          echo "----- ticker.json (preview) -----"
          head -n 80 ticker.json || (echo "ticker.json NICHT erzeugt" && exit 1)
          echo "---------------------------------"

      - name: Rebase onto latest main
        run: |
          git config user.name  "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git pull --rebase origin main

      - name: Commit & push if changed
        uses: EndBug/add-and-commit@v9
        with:
          add: "ticker.json"
          message: "chore: daily ticker update"
          default_author: github_actions
